# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#about-the-dependabotyml-file
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    reviewers:
      - "stroblme"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    open-pull-requests-limit: 5
    schedule:
      day: "monday"
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "stroblme"
