name: Testing on Review
on:
  pull_request:
    types: [review_requested]
  workflow_call:
    inputs:
      runner_label:
        required: false
        type: string
permissions:
  contents: write
jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner_label: ${{ steps.set-runner.outputs.runner_label }}
    steps:
      - name: Set runner
        if: "${{ github.event.inputs.runner_label == '' }}"
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner_label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner_label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi
      - name: Get runner
        if: "${{ github.event.inputs.runner_label != '' }}"
        id: get-runner
        run: echo ${{ github.event.inputs.runner_label }} >> $GITHUB_OUTPUT
  test-expensive:
    if: ${{ (github.actor != 'github-actions[bot]') }}
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner_label }}
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev
    - name: Test with pytest
      run: poetry run pytest --cov=qml_essentials --cov-report html --dist load -m "expensive" -n auto
    - name: Share coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/