name: Testing
on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
permissions:
  contents: write
jobs:
  test-created:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev
    - name: Test with pytest
      run: |
        poetry run pytest "not expensive" -n auto
  test-approved:
    if: ${{ (github.event.review.state == 'approved') || (github.ref == 'refs/heads/main') }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev
    - name: Test with pytest
      run: |
        poetry run coverage run --parallel-mode -m pytest -n auto
        poetry run coverage combine
        poetry run coverage report -m
        poetry run coverage html
    - name: Share coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/